"""
    Contains classes that store information about certain traits
    and constructors the text / mail has to follow
"""


class Sender:
    """
        Definition for data construct that stores relevant sender information
    """
    def __init__(self):
        pass

    def config(self):
        """
        Fills the requirements for this constructor.
        Uses getters and setters to check data validity
        :returns: True / Exeption
        """

    def get_string(self):
        """
        Returns a string that is generated by the fucntion to fill in into the main mail / text
        :returns: string
        """


class Date:
    """
        Definition for data construct that stores the date
    """
    def __init__(self):
        pass

    def config(self):
        """
        Fills the requirements for this constructor.
        Uses getters and setters to check data validity
        :returns: True / Exeption
        """

    def get_string(self):
        """
        Returns a string that is generated by the fucntion to fill in into the main mail / text
        :returns: string
        """


class Adress:
    """
        Definition for data construct that stores relevant adress information.
        e.g. mail, cc bcc
    """
    def __init__(self):
        pass

    def config(self):
        """
        Fills the requirements for this constructor.
        Uses getters and setters to check data validity
        :returns: True / Exeption
        """

    def get_string(self):
        """
        Returns a string that is generated by the fucntion to fill in into the main mail / text
        :returns: string
        """


class Recipient:
    """
        Definition for data construct that stores relevant recipient information
        e.g. name, birthday, character information / keywords
    """
    def __init__(self):
        pass

    def config(self):
        """
        Fills the requirements for this constructor.
        Uses getters and setters to check data validity
        :returns: True / Exeption
        """

    def get_string(self):
        """
        Returns a string that is generated by the fucntion to fill in into the main mail / text
        :returns: string
        """
